baseURL      = 'http://ham.neocloud.tw/'
languageCode = 'zh-TW'
title        = 'NeoNetwork Ham Radio Blog'
theme        = 'brutalist-minimalist'
relativeURLs = true

[markup]
  [markup.highlight]
    noClasses=false
#  [markup.tableOfContents]
#    endLevel = 4
#    ordered = true
#    startLevel = 3


[params]

	# --- Site config ---------------------------------

	subtitle         = 'A simple blog for Ham Radio'
	siteBasename     = 'NeoNetwork Ham Radio Blog'
	copyright        = "NeoCloud"
	copyrightYear    = "2021-2023" # for site in case there is no page date, not yet implemented

	# --- Style tweaking ------------------------------

	bloglistLength   = 5            # number of blog posts to turn up at front page, 0 for
	                                # none.

	highlightStyle   = 'emacs'      # builtin styles: emacs, pygment. Empty for none.
	enableKatex      = true         # If off, math is rendered as plain text (verbatim)

	# Only set the following parameters if you create
	# the css files referenced in them.
	#
	styleParametersCSS      = 'css/style-parameters.css'
	styleTweaksCSS          = 'css/style-tweaks.css'
	# fontSettingsCSS         = 'css/font-settings.css'
	
	# Fall back to more minimalism
	styleMinimalistOnly = false
	noStylingAtAll      = false      # we use that to see how this might render in text mode

	# Overriding responsiveness
	# responsivenessLimitsCSS = 'css/NONE.css'
	# limitCompactMenu      = 55
	# limitHamburgerMenu    = 40	    
	# limitCompactLayout    = 30	    
	# limitNarrowLayout     = 25	  
	# limitVeryNarrowLayout = 17

	averageCharWidth        = 0.7
