baseURL      = 'http://ham.neocloud.tw/'
languageCode = 'zh-TW'
title        = 'NeoNetwork Ham Radio Blog'
theme        = 'hugo-book'
relativeURLs = true
copyright    = "© NeoNetwork, Licensed under CC4.0 BY-SA"
enableGitInfo = true

#[markup]
#  [markup.highlight]
#    noClasses=false
#  [markup.tableOfContents]
#    endLevel = 4
#    ordered = true
#    startLevel = 3


[params]
	siteBasename     = 'NeoNetwork Ham Radio Blog'
	subtitle         = 'A simple blog for Ham Radio'
	copyright        = "NeoCloud"
	copyrightYear    = "2021-2023" # for site in case there is no page date, not yet implemented

	BookTheme = 'dark'
	BookRepo = 'https://github.com/NeoCloud/HamRadio-Homepage'
	BookPortableLinks = true
	BookSection = '*'